
AVR_TOOLS_PATH = /home/tools/arduino/avr/sdk/usr/bin
ARDUINO_DIR  = /home/tools/arduino/arduino-1.0
ARDUINO_MK_PATH = /home/tools/arduino/avr/projects/mkbuild
AVRDUDE = /home/tools/arduino/arduino-1.0/hardware/tools/avrdude
AVRDUDE_CONF = /home/tools/arduino/arduino-1.0/hardware/tools/avrdude.conf

TARGET       = blink
ARDUINO_LIBS = SPI EEPROM

BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0

include $(ARDUINO_MK_PATH)/Arduino.mk

